DROP TABLE ACTIVIDAD CASCADE CONSTRAINTS;
DROP TABLE ALERTA CASCADE CONSTRAINTS;
DROP TABLE APROBAR CASCADE CONSTRAINTS;
DROP TABLE ASISTENCIA CASCADE CONSTRAINTS;
DROP TABLE CHECKLIST CASCADE CONSTRAINTS;
DROP TABLE CONTRATO CASCADE CONSTRAINTS;
DROP TABLE EMPRESA CASCADE CONSTRAINTS;
DROP TABLE FONDO_MONETARIO CASCADE CONSTRAINTS;
DROP TABLE INFORME CASCADE CONSTRAINTS;
DROP TABLE INTERACCION CASCADE CONSTRAINTS;
DROP TABLE LOGIN CASCADE CONSTRAINTS;
DROP TABLE MEJORA CASCADE CONSTRAINTS;
DROP TABLE PAGO CASCADE CONSTRAINTS;
DROP TABLE PROFESION CASCADE CONSTRAINTS;
DROP TABLE REPORTE CASCADE CONSTRAINTS;
DROP TABLE SERVICIO CASCADE CONSTRAINTS;
DROP TABLE TIPO_ACTIVIDAD CASCADE CONSTRAINTS;
DROP TABLE TIPO_USUARIO CASCADE CONSTRAINTS;
DROP TABLE USUARIO CASCADE CONSTRAINTS;

CREATE TABLE ACTIVIDAD (
    ID_ACTIVIDAD           NUMBER(8) NOT NULL,
    ID_SERVICIO   NUMBER(8) NOT NULL,
    NOMBRE_ACTIVIDAD       VARCHAR2(50),
    DESCRIPCION_ACTIVIDAD  VARCHAR2(255),
    ESTADO                 NUMBER(1),
    FECHA_INICIO           DATE,
    FECHA_TERMINO          DATE
);

ALTER TABLE ACTIVIDAD ADD CONSTRAINT ACTIVIDAD_PK PRIMARY KEY ( ID_ACTIVIDAD );

CREATE TABLE ALERTA (
    ID_ALERTA                         NUMBER(8) NOT NULL, 
    ID_TIPO_ACTIVIDAD                 NUMBER(8),
    NOMBRE_ALERTA                     VARCHAR2(50),
    DESCRIPCION_ALERTA                VARCHAR2(255),
    ESTADO                            NUMBER(1),
    FECHA_ALERTA                     DATE
);

ALTER TABLE ALERTA ADD CONSTRAINT ALERTA_PK PRIMARY KEY ( ID_ALERTA );

CREATE TABLE APROBAR (
    ID_APROBACION             NUMBER(8) NOT NULL,
    ID_PROFESION  NUMBER(8) NOT NULL,
    ID_MEJORA          NUMBER(8) NOT NULL,
    NOMBRE_APROBACION         VARCHAR2(50),
    DESCRIPCION               VARCHAR2(255),
    ESTADO                    NUMBER(1),
    FECHA_APROBACION              DATE
);

ALTER TABLE APROBAR ADD CONSTRAINT APROBAR_PK PRIMARY KEY ( ID_APROBACION );

CREATE TABLE ASISTENCIA (
    ID_ASISTENCIA                     NUMBER(8) NOT NULL, 
    ID_TIPO_ACTIVIDAD                 NUMBER(8),
    DESCRIPCION_ASISTENCIA            VARCHAR2(255),
    ESTADO                            NUMBER(1),
    FECHA_EMISION                     DATE
);

ALTER TABLE ASISTENCIA ADD CONSTRAINT ASISTENCIA_PK PRIMARY KEY ( ID_ASISTENCIA );

CREATE TABLE CHECKLIST (
    ID_CHECKLIST                      NUMBER(8) NOT NULL, 
    ID_TIPO_ACTIVIDAD  NUMBER(8),
    ARCHIVO                           VARCHAR2(255),
    NOMBRE_CHECKLIST                  VARCHAR2(60),
    DESCRIPCION                       VARCHAR2(255),
    FECHA_EMISION                     DATE
);

ALTER TABLE CHECKLIST ADD CONSTRAINT CHECKLIST_PK PRIMARY KEY ( ID_CHECKLIST );

CREATE TABLE CONTRATO (
    FOLIO_CONTRATO                NUMBER(8) NOT NULL,
    ID_TIPO_USUARIO               NUMBER(8) NOT NULL,
    FECHA_CONTRATO                DATE,
    PLAZO_CONTRATO                VARCHAR2(50),  
    MONTO_PAGO                    NUMBER(8),
    MODIFICADO                    NUMBER(1),  
    ESTADO                        NUMBER(1)
);

ALTER TABLE CONTRATO ADD CONSTRAINT CONTRATO_PK PRIMARY KEY ( FOLIO_CONTRATO );

CREATE TABLE EMPRESA (
    RUT_EMPRESA                   VARCHAR2(15) NOT NULL,
    ID_TIPO_USUARIO  NUMBER(8),
    RUT_USUARIO                   VARCHAR2(12),
    RAZON_SOCIAL_EMPRESA          VARCHAR2(50),
    DIRECCION_EMPRESA             VARCHAR2(255),
    TELEFONO_EMPRESA              NUMBER(15),
    CORREO_EMPRESA                VARCHAR2(255),
    PAGINA_WEB_EMPRESA            VARCHAR2(255)
);

ALTER TABLE EMPRESA ADD CONSTRAINT EMPRESA_PK PRIMARY KEY ( RUT_EMPRESA );

CREATE TABLE FONDO_MONETARIO (
    ID_FONDO                 NUMBER(8) NOT NULL,
    FOLIO_CONTRATO           NUMBER(8),
    MONTO_ABONO              NUMBER(8),
    FECHA_ABONO              DATE
);

ALTER TABLE FONDO_MONETARIO ADD CONSTRAINT FONDO_MONETARIO_PK PRIMARY KEY ( ID_FONDO );

CREATE TABLE INFORME (
    ID_INFORME                        NUMBER(8) NOT NULL, 
    ID_TIPO_ACTIVIDAD  NUMBER(8),
    NOMBRE_INFORME                    VARCHAR2(50),
    ARCHIVO VARCHAR2(255),
    DESCRIPCION_INFORME               VARCHAR2(50),
    FECHA_EMISION                     DATE
);

ALTER TABLE INFORME ADD CONSTRAINT INFORME_PK PRIMARY KEY ( ID_INFORME );

CREATE TABLE INTERACCION (
    ID_INTERACCION                    NUMBER(8) NOT NULL, 
    ID_TIPO_ACTIVIDAD                 NUMBER(8),
    ID_PROFESIONAL                    VARCHAR2(11) NOT NULL,
    FECHA_INTERACION                  DATE
);

ALTER TABLE INTERACCION ADD CONSTRAINT INTERACCION_PK PRIMARY KEY ( ID_INTERACCION );

CREATE TABLE LOGIN (
    ID_LOGIN                      NUMBER(8) NOT NULL,
    CONTRASEÑA_USUARIO                    VARCHAR2(255),
    ID_TIPO_USUARIO  NUMBER(8) NOT NULL
);

ALTER TABLE LOGIN ADD CONSTRAINT LOGIN_PK PRIMARY KEY ( ID_LOGIN );

CREATE TABLE MEJORA (
    ID_MEJORA                         NUMBER(8) NOT NULL, 
    ID_TIPO_ACTIVIDAD  NUMBER(8),
    NOMBRE_MEJORA                     VARCHAR2(50),
    DESCRIPCION_MEJORA                VARCHAR2(255),
    ARCHIVO                           VARCHAR2(255),
    ESTADO                            NUMBER(1),
    FECHA_INICIO                      DATE,
    FECHA_TERMINO                     DATE
);

ALTER TABLE MEJORA ADD CONSTRAINT MEJORA_PK PRIMARY KEY ( ID_MEJORA );

CREATE TABLE PAGO (
    ID_PAGO               NUMBER(8) NOT NULL,
    ID_SERVICIO  NUMBER(8) NOT NULL,
    VALOR_TOTAL           NUMBER(8),
    DESCRIPCION VARCHAR2(255),
    FECHA_PAGO            DATE
);

ALTER TABLE PAGO ADD CONSTRAINT PAGO_PK PRIMARY KEY ( ID_PAGO );

CREATE TABLE PROFESION (
    ID_PROFESION                  NUMBER(8) NOT NULL,
    ID_TIPO_USUARIO  NUMBER(8),
    NOMBRE_PROFESION              VARCHAR2(50)
);

ALTER TABLE PROFESION ADD CONSTRAINT PROFESIONAL_PK PRIMARY KEY ( ID_PROFESION );

CREATE TABLE REPORTE (
    ID_REPORTE                        NUMBER(8) NOT NULL, 
    ID_TIPO_ACTIVIDAD   NUMBER(8),
    NOMBRE_REPORTE                    VARCHAR2(50),
    ARCHIVO         VARCHAR2(255),
    DESCRIPCION_REPORTE               VARCHAR2(255),
    FECHA_EMISION                     DATE
);

ALTER TABLE REPORTE ADD CONSTRAINT REPORTE_PK PRIMARY KEY ( ID_REPORTE );

CREATE TABLE SERVICIO (
    ID_SERVICIO              NUMBER(8) NOT NULL,
    FOLIO_CONTRATO          NUMBER(8) NOT NULL,
    NOMBRE_SERVICIO          VARCHAR2(50),
    VALOR_SERVICIO          NUMBER(8),
    DESCRIPCION_SERVICIO     VARCHAR2(255),
    FECHA_INICIO             DATE,
    FECHA_TERMINO            DATE,
    ESTADO                   NUMBER(1),
    PAGADO                   NUMBER(1)
);

ALTER TABLE SERVICIO ADD CONSTRAINT SERVICIO_PK PRIMARY KEY ( ID_SERVICIO );

CREATE TABLE TIPO_ACTIVIDAD (
    ID_TIPO_ACTIVIDAD       NUMBER(8) NOT NULL,
    ID_ACTIVIDAD  NUMBER(8) NOT NULL,
    NOMBRE_TIPO_ACTIVIDAD   VARCHAR2(50)
);

ALTER TABLE TIPO_ACTIVIDAD ADD CONSTRAINT TIPO_ACTIVIDAD_PK PRIMARY KEY ( ID_TIPO_ACTIVIDAD );

CREATE TABLE TIPO_USUARIO (
    ID_TIPO_USUARIO      NUMBER(8) NOT NULL,
    RUT_USUARIO  NVARCHAR2(11) NOT NULL,
    TIPO  VARCHAR2(50)
);

ALTER TABLE TIPO_USUARIO ADD CONSTRAINT TIPO_USUARIO_PK PRIMARY KEY ( ID_TIPO_USUARIO );

CREATE TABLE USUARIO (
    RUT_USUARIO        VARCHAR2(11) NOT NULL,
    NOMBRE_USUARIO     VARCHAR2(50),
    APELLIDO_USUARIO   VARCHAR2(50),
    TELEFONO_USUARIO   NUMBER(12),
    CORREO_USUARIO     VARCHAR2(255),
    DOMICILIO_USUARIO  VARCHAR2(255),
    HABILITADO         NUMBER(1)
);

ALTER TABLE USUARIO ADD CONSTRAINT TABLA_USUARIO_PK PRIMARY KEY ( RUT_USUARIO );

ALTER TABLE ACTIVIDAD
    ADD CONSTRAINT ACTIVIDAD_SERVICIO_FK FOREIGN KEY ( ID_SERVICIO )
        REFERENCES SERVICIO ( ID_SERVICIO );

ALTER TABLE ALERTA
    ADD CONSTRAINT ALERTA_TIPO_ACTIVIDAD_FK FOREIGN KEY ( ID_TIPO_ACTIVIDAD )
        REFERENCES TIPO_ACTIVIDAD ( ID_TIPO_ACTIVIDAD );

ALTER TABLE APROBAR
    ADD CONSTRAINT APROBAR_MEJORA_FK FOREIGN KEY ( ID_MEJORA )
        REFERENCES MEJORA ( ID_MEJORA );

ALTER TABLE APROBAR
    ADD CONSTRAINT APROBAR_PROFESIONAL_FK FOREIGN KEY ( ID_PROFESION )
        REFERENCES PROFESION ( ID_PROFESION );

ALTER TABLE ASISTENCIA
    ADD CONSTRAINT ASISTENCIA_TIPO_ACTIVIDAD_FK FOREIGN KEY ( ID_TIPO_ACTIVIDAD )
        REFERENCES TIPO_ACTIVIDAD ( ID_TIPO_ACTIVIDAD );

ALTER TABLE CHECKLIST
    ADD CONSTRAINT CHECKLIST_TIPO_ACTIVIDAD_FK FOREIGN KEY ( ID_TIPO_ACTIVIDAD )
        REFERENCES TIPO_ACTIVIDAD ( ID_TIPO_ACTIVIDAD );

ALTER TABLE CONTRATO
    ADD CONSTRAINT CONTRATO_TIPO_USUARIO_FK FOREIGN KEY ( ID_TIPO_USUARIO )
        REFERENCES TIPO_USUARIO ( ID_TIPO_USUARIO );

ALTER TABLE EMPRESA
    ADD CONSTRAINT EMPRESA_TIPO_USUARIO_FK FOREIGN KEY ( ID_TIPO_USUARIO )
        REFERENCES TIPO_USUARIO ( ID_TIPO_USUARIO );

ALTER TABLE FONDO_MONETARIO
    ADD CONSTRAINT FONDO_MONETARIO_CONTRATO_FK FOREIGN KEY ( FOLIO_CONTRATO )
        REFERENCES CONTRATO ( FOLIO_CONTRATO );

ALTER TABLE INFORME
    ADD CONSTRAINT INFORME_TIPO_ACTIVIDAD_FK FOREIGN KEY ( ID_TIPO_ACTIVIDAD )
        REFERENCES TIPO_ACTIVIDAD ( ID_TIPO_ACTIVIDAD );

ALTER TABLE INTERACCION
    ADD CONSTRAINT INTERACCION_TIPO_ACTIVIDAD_FK FOREIGN KEY ( ID_TIPO_ACTIVIDAD )
        REFERENCES TIPO_ACTIVIDAD ( ID_TIPO_ACTIVIDAD );

ALTER TABLE LOGIN
    ADD CONSTRAINT LOGIN_TIPO_USUARIO_FK FOREIGN KEY ( ID_TIPO_USUARIO )
        REFERENCES TIPO_USUARIO ( ID_TIPO_USUARIO );

ALTER TABLE MEJORA
    ADD CONSTRAINT MEJORA_TIPO_ACTIVIDAD_FK FOREIGN KEY ( ID_TIPO_ACTIVIDAD )
        REFERENCES TIPO_ACTIVIDAD ( ID_TIPO_ACTIVIDAD );

ALTER TABLE PAGO
    ADD CONSTRAINT PAGO_SERVICIO_FK FOREIGN KEY ( ID_SERVICIO )
        REFERENCES SERVICIO ( ID_SERVICIO );

ALTER TABLE PROFESION
    ADD CONSTRAINT PROFESION_TIPO_USUARIO_FK FOREIGN KEY ( ID_TIPO_USUARIO )
        REFERENCES TIPO_USUARIO ( ID_TIPO_USUARIO );

ALTER TABLE REPORTE
    ADD CONSTRAINT REPORTE_TIPO_ACTIVIDAD_FK FOREIGN KEY ( ID_TIPO_ACTIVIDAD )
        REFERENCES TIPO_ACTIVIDAD ( ID_TIPO_ACTIVIDAD );

ALTER TABLE SERVICIO
    ADD CONSTRAINT SERVICIO_CONTRATO_FK FOREIGN KEY ( FOLIO_CONTRATO )
        REFERENCES CONTRATO ( FOLIO_CONTRATO );

ALTER TABLE TIPO_ACTIVIDAD
    ADD CONSTRAINT TIPO_ACTIVIDAD_ACTIVIDAD_FK FOREIGN KEY ( ID_ACTIVIDAD )
        REFERENCES ACTIVIDAD ( ID_ACTIVIDAD );




